// The NBA schedule, read at runtime from the file the site publishes.
//
// There is exactly ONE schedule file in this project: public/data/schedule.json,
// generated by `node scripts/build-schedule.js`. These functions used to bundle
// their own copies of it, which silently went stale — fetching the published
// file instead means a site deploy updates the emails too, with no function
// redeploy. That matters in December, when the NBA assigns the two NBA Cup
// dates each team is missing and the file is regenerated.
//
// Set SCHEDULE_URL in the function's secrets to point at a different origin
// (e.g. a Netlify deploy preview) when testing.

const DEFAULT_URL = "https://fantasygoats.guru/data/schedule.json";
import { type FantasyWeeks, matchupDates } from "./fantasy-calendar.ts";

// date (YYYY-MM-DD, US Eastern) → tricodes of the teams playing that day
export type Schedule = Record<string, string[]>;

let cached: Schedule | null = null;
let cachedWeeks: FantasyWeeks | null = null;

export async function getMatchupDates(matchup: { week_start?: string; week_end?: string } = {}) {
  if (matchup.week_start && matchup.week_end) return matchupDates({}, matchup);
  if (!cachedWeeks) {
    const scheduleUrl = Deno.env.get("SCHEDULE_URL") ?? DEFAULT_URL;
    const weeksUrl = Deno.env.get("WEEKS_URL") ?? new URL("weeks.json", scheduleUrl).href;
    const response = await fetch(weeksUrl);
    if (!response.ok) throw new Error(`Failed to load fantasy weeks: HTTP ${response.status}`);
    const data = await response.json();
    if (!data.weeks || !Object.keys(data.weeks).length) throw new Error("Fantasy matchup calendar is empty");
    cachedWeeks = data.weeks;
  }
  return matchupDates(cachedWeeks!, matchup);
}

/**
 * Fetches the schedule once per function instance.
 *
 * Throws if the file cannot be read. That is deliberate: these functions send
 * matchup projections, and a projection built from a missing schedule would be
 * silently wrong for every recipient. Failing loudly is the safer outcome.
 */
export async function getSchedule(): Promise<Schedule> {
  if (cached) return cached;

  const url = Deno.env.get("SCHEDULE_URL") ?? DEFAULT_URL;
  const res = await fetch(url, { headers: { Accept: "application/json" } });
  if (!res.ok) {
    throw new Error(`Failed to load schedule from ${url}: HTTP ${res.status}`);
  }

  const data = (await res.json()) as Schedule;
  const days = Object.keys(data).length;
  if (!days) throw new Error(`Schedule from ${url} is empty`);

  console.log(`Loaded schedule: ${days} game days (${url})`);
  cached = data;
  return data;
}

/** Tricodes playing on a given US Eastern date, or [] if none. */
export async function teamsPlayingOn(dateStr: string): Promise<string[]> {
  const schedule = await getSchedule();
  return schedule[dateStr] ?? [];
}
